### ISSUE TITLE
letters with ae converted to special char Ä

### ISSUE THREAD

**Issue by vignesh511989** [NiklasMencke/nextjs-breadcrumbs#24]
![Screen Shot 2021-08-11 at 4 44 29 PM](https://user-images.githubusercontent.com/59625151/128970996-b3212929-dcaa-450f-8f0b-efbad7d78bd1.png)
Is it possible to fix this?

Thanks

**Comment by aheilemann** [comment]
I have the same issue from ae to ä.
It stems from this line in index.js
`transformedTitle = transformedTitle.replace(/-/g, ' ').replace(/oe/g, 'ö').replace(/ae/g, 'ä').replace(/ue/g, 'ü').replace(/\?.*/, '');`

**Comment by NiklasMencke** [comment]
Good idea, since the character replacement shouldn't happen per default anyway. 

I removed the default character replacement and added a new prop that allows custom replacement.

See PR here: https://github.com/NiklasMencke/nextjs-breadcrumbs/pull/28

Example: 
const Example = () => {
  return (
    <Breadcrumbs
      useDefaultStyle={true}
      replaceCharacterList={[{ from: '.', to: ' ' }]}
    />
  );
};
